In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
data_file = os.path.join("data","all_month.csv")
all_month_pd = pd.read_csv(data_file)
all_month_pd.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2018-06-13T00:48:28.750Z,19.420666,-155.277664,1.65,1.77,ml,14.0,91.0,0.004074,0.23,...,2018-06-13T00:54:09.600Z,"4km WSW of Volcano, Hawaii",earthquake,0.61,0.52,0.15,6.0,automatic,hv,hv
1,2018-06-13T00:45:44.130Z,33.520167,-116.795333,4.29,0.47,ml,20.0,47.0,0.066220,0.13,...,2018-06-13T00:49:18.268Z,"11km NE of Aguanga, CA",earthquake,0.22,0.53,0.15,17.0,automatic,ci,ci
2,2018-06-13T00:45:09.190Z,19.306000,-155.251495,5.21,2.26,ml,25.0,110.0,0.035360,0.13,...,2018-06-13T00:50:59.630Z,"13km S of Volcano, Hawaii",earthquake,0.42,0.77,0.26,9.0,automatic,hv,hv
3,2018-06-13T00:43:08.050Z,19.407333,-155.279007,0.38,2.11,ml,18.0,63.0,0.011340,0.14,...,2018-06-13T00:48:49.780Z,"5km WSW of Volcano, Hawaii",earthquake,0.18,0.25,0.34,9.0,automatic,hv,hv
4,2018-06-13T00:41:18.360Z,38.763832,-122.710167,1.61,0.54,md,7.0,217.0,0.009553,0.03,...,2018-06-13T00:42:56.850Z,"2km SW of Anderson Springs, CA",earthquake,0.72,0.97,0.14,3.0,automatic,nc,nc

In [3]:
all_month_pd['time'] = pd.to_datetime(all_month_pd['time'])

In [4]:
all_month_pd.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2018-06-13 00:48:28.750,19.420666,-155.277664,1.65,1.77,ml,14.0,91.0,0.004074,0.23,...,2018-06-13T00:54:09.600Z,"4km WSW of Volcano, Hawaii",earthquake,0.61,0.52,0.15,6.0,automatic,hv,hv
1,2018-06-13 00:45:44.130,33.520167,-116.795333,4.29,0.47,ml,20.0,47.0,0.066220,0.13,...,2018-06-13T00:49:18.268Z,"11km NE of Aguanga, CA",earthquake,0.22,0.53,0.15,17.0,automatic,ci,ci
2,2018-06-13 00:45:09.190,19.306000,-155.251495,5.21,2.26,ml,25.0,110.0,0.035360,0.13,...,2018-06-13T00:50:59.630Z,"13km S of Volcano, Hawaii",earthquake,0.42,0.77,0.26,9.0,automatic,hv,hv
3,2018-06-13 00:43:08.050,19.407333,-155.279007,0.38,2.11,ml,18.0,63.0,0.011340,0.14,...,2018-06-13T00:48:49.780Z,"5km WSW of Volcano, Hawaii",earthquake,0.18,0.25,0.34,9.0,automatic,hv,hv
4,2018-06-13 00:41:18.360,38.763832,-122.710167,1.61,0.54,md,7.0,217.0,0.009553,0.03,...,2018-06-13T00:42:56.850Z,"2km SW of Anderson Springs, CA",earthquake,0.72,0.97,0.14,3.0,automatic,nc,nc

In [5]:
all_month_pd['Date'] = all_month_pd['time'].dt.strftime('%Y-%m-%d')
all_month_pd['Time'] = all_month_pd['time'].dt.strftime('%H:%M:%S')

In [6]:
all_month_pd.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,Date,Time
0,2018-06-13 00:48:28.750,19.420666,-155.277664,1.65,1.77,ml,14.0,91.0,0.004074,0.23,...,earthquake,0.61,0.52,0.15,6.0,automatic,hv,hv,2018-06-13,00:48:28
1,2018-06-13 00:45:44.130,33.520167,-116.795333,4.29,0.47,ml,20.0,47.0,0.066220,0.13,...,earthquake,0.22,0.53,0.15,17.0,automatic,ci,ci,2018-06-13,00:45:44
2,2018-06-13 00:45:09.190,19.306000,-155.251495,5.21,2.26,ml,25.0,110.0,0.035360,0.13,...,earthquake,0.42,0.77,0.26,9.0,automatic,hv,hv,2018-06-13,00:45:09
3,2018-06-13 00:43:08.050,19.407333,-155.279007,0.38,2.11,ml,18.0,63.0,0.011340,0.14,...,earthquake,0.18,0.25,0.34,9.0,automatic,hv,hv,2018-06-13,00:43:08
4,2018-06-13 00:41:18.360,38.763832,-122.710167,1.61,0.54,md,7.0,217.0,0.009553,0.03,...,earthquake,0.72,0.97,0.14,3.0,automatic,nc,nc,2018-06-13,00:41:18

In [7]:
cleaned_df = all_month_pd[["Date","Time","latitude","longitude","mag","type","place"]].copy()

In [8]:
cleaned_df.head()

,Date,Time,latitude,longitude,mag,type,place
0,2018-06-13,00:48:28,19.420666,-155.277664,1.77,earthquake,"4km WSW of Volcano, Hawaii"
1,2018-06-13,00:45:44,33.520167,-116.795333,0.47,earthquake,"11km NE of Aguanga, CA"
2,2018-06-13,00:45:09,19.306000,-155.251495,2.26,earthquake,"13km S of Volcano, Hawaii"
3,2018-06-13,00:43:08,19.407333,-155.279007,2.11,earthquake,"5km WSW of Volcano, Hawaii"
4,2018-06-13,00:41:18,38.763832,-122.710167,0.54,earthquake,"2km SW of Anderson Springs, CA"

In [9]:
cleaned_df["place"] = cleaned_df["place"].str.split("of").str[1]

In [11]:
cleaned_df

,Date,Time,latitude,longitude,mag,type,place
0,2018-06-13,00:48:28,19.420666,-155.277664,1.77,earthquake,"Volcano, Hawaii"
1,2018-06-13,00:45:44,33.520167,-116.795333,0.47,earthquake,"Aguanga, CA"
2,2018-06-13,00:45:09,19.306000,-155.251495,2.26,earthquake,"Volcano, Hawaii"
3,2018-06-13,00:43:08,19.407333,-155.279007,2.11,earthquake,"Volcano, Hawaii"
4,2018-06-13,00:41:18,38.763832,-122.710167,0.54,earthquake,"Anderson Springs, CA"
5,2018-06-13,00:40:24,19.410667,-155.269333,2.40,earthquake,"Volcano, Hawaii"
6,2018-06-13,00:39:11,19.427500,-155.255829,2.58,earthquake,"Volcano, Hawaii"
7,2018-06-13,00:38:54,19.412834,-155.272659,1.97,earthquake,"Volcano, Hawaii"
8,2018-06-13,00:38:29,33.505167,-117.105000,0.61,earthquake,"Temecula, CA"
9,2018-06-13,00:36:30,19.427834,-155.252502,1.86,earthquake,"Volcano, Hawaii"
10,2018-06-13,00:32:47,35.920167,-117.719000,1.39,earthquake,"Little Lake, CA"
11,2018-06-13,00:32:37,19.385500,-155.337830,2.68,earthquake,"Volcano, Hawaii"
12,2018-06-13,00:31:42,38.818333,-122.812332,0.55,earthquake,"The Geysers, CA"
13,2018-06-13,00:31:41,19.404833,-155.257507,2.25,earthquake,"Volcano, Hawaii"
14,2018-06-13,00:30:29,33.716167,-116.776833,0.56,earthquake,"Idyllwild, CA"
15,2018-06-13,00:28:57,19.400667,-155.269669,2.52,earthquake,"Volcano, Hawaii"
16,2018-06-13,00:28:30,33.478500,-116.472333,1.22,earthquake,"Anza, CA"
17,2018-06-13,00:24:33,19.430166,-155.302994,1.75,earthquake,"Volcano, Hawaii"
18,2018-06-13,00:17:30,19.409166,-155.279495,2.10,earthquake,"Volcano, Hawaii"
19,2018-06-13,00:15:29,19.398834,-155.279999,1.84,earthquake,"Volcano, Hawaii"
20,2018-06-13,00:15:06,33.504333,-116.802000,0.49,earthquake,"Aguanga, CA"
21,2018-06-13,00:11:53,61.812500,-149.258800,1.40,earthquake,"Fishhook, Alaska"
22,2018-06-13,00:10:39,19.451500,-155.227997,2.26,earthquake,"Volcano, Hawaii"
23,2018-06-13,00:07:51,19.410833,-155.251328,1.97,earthquake,"Volcano, Hawaii"
24,2018-06-13,00:05:50,19.419167,-155.270828,2.30,earthquake,"Volcano, Hawaii"
25,2018-06-13,00:02:10,19.417499,-155.275162,2.16,earthquake,"Volcano, Hawaii"
26,2018-06-13,00:01:17,19.429333,-155.288666,1.84,earthquake,"Volcano, Hawaii"
27,2018-06-12,23:56:37,19.416833,-155.275500,3.43,earthquake,"Volcano, Hawaii"
28,2018-06-12,23:55:23,38.730200,-117.178200,2.20,earthquake,"Gabbs, Nevada"
29,2018-06-12,23:54:00,19.425333,-155.251007,2.41,earthquake,"Volcano, Hawaii"
...,...,...,...,...,...,...,...
15468,2018-05-14,02:16:36,63.180900,-152.272300,1.10,earthquake,"Talkeetna, Alaska"
15469,2018-05-14,02:11:33,38.045300,-118.961900,1.00,earthquake,"Bridgeport, California"
15470,2018-05-14,02:05:38,19.455833,-154.929000,1.61,earthquake,"Leilani Estates, Hawaii"
15471,2018-05-14,02:04:46,65.780300,-162.841300,2.50,earthquake,"Kotzebue, Alaska"
15472,2018-05-14,02:03:56,19.414667,-155.283167,1.70,earthquake,"Volcano, Hawaii"
15473,2018-05-14,02:01:45,65.732200,-148.431200,0.80,earthquake,"Ester, Alaska"
15474,2018-05-14,01:57:08,38.868333,-122.815000,1.28,earthquake,"Cobb, CA"
15475,2018-05-14,01:54:13,61.311100,-147.280300,1.10,earthquake,"Valdez, Alaska"
15476,2018-05-14,01:52:14,1.968300,96.670300,4.00,earthquake,"Sinabang, Indonesia"
15477,2018-05-14,01:45:33,65.747800,-151.109200,0.80,earthquake,"Tanana, Alaska"
15478,2018-05-14,01:32:21,58.784900,-134.455200,1.90,earthquake,"Juneau, Alaska"
15479,2018-05-14,01:29:16,19.456667,-154.876663,2.39,earthquake,"Leilani Estates, Hawaii"
15480,2018-05-14,01:26:24,19.431167,-155.252667,2.92,earthquake,"Volcano, Hawaii"
15481,2018-05-14,01:23:56,36.612167,-121.163333,1.67,earthquake,"Pinnacles, CA"
15482,2018-05-14,01:18:55,53.486800,-165.341200,1.90,earthquake,"Akutan, Alaska"
15483,2018-05-14,01:18:09,66.842200,-150.238300,0.90,earthquake,"Coldfoot, Alaska"
15484,2018-05-14,01:17:45,31.266100,-103.726500,2.80,earthquake,"Pecos, Texas"
15485,2018-05-14,01:17:21,33.062667,-115.896167,1.32,earthquake,"Ocotillo Wells, CA"
15486,2018-05-14,01:17:07,33.070833,-115.869167,0.85,earthquake,"Westmorland, CA"
15487,2018-05-14,01:14:47,33.070000,-115.909333,2.26,earthquake,"Ocotillo Wells, CA"
15488,2018-05-14,01:14:35,33.510000,-116.797833,0.42,earthquake,"Aguanga, CA"
15489,2018-05-14,01:12:35,33.619000,-116.659500,0.28,earthquake,"Anza, CA"
15490,2018-05-14,01:08:38,35.997833,-120.885000,0.88,earthquake,"San Ardo, CA"
15491,2018-05-14,01:08:09,53.526000,-165.282800,1.80,earthquake,"Akutan, Alaska"
15492,2018-05-14,01:03:42,62.851000,-150.522600,1.10,earthquake,"Talkeetna, Alaska"
15493,2018-05-14,01:01:47,37.660500,-118.905333,0.74,earthquake,"Mammoth Lakes, CA"
15494,2018-05-14,01:01:15,37.660167,-118.906667,0.76,earthquake,"Mammoth Lakes, CA"
15495,2018-05-14,01:01:02,43.169333,-111.448667,2.05,earthquake,"Ammon, Idaho"
15496,2018-05-14,01:00:32,62.695900,-152.674400,1.40,earthquake,"Talkeetna, Alaska"
15497,2018-05-14,00:56:24,43.160833,-111.373667,1.41,earthquake,"Hoback, Wyoming"